### ISSUE TITLE
Logika | Gracz - człowiek

### ISSUE THREAD

**Issue by KlaraGajaszek** [KlaraGajaszek/CC2020Javascript#5]
Kryteria akceptacji
Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.

 Funkcja zwracająca obiekt reprezentujący gracza - człowieka.
 Obiekt gracza pozwala zadać graczowi pytanie oraz udzielić odpowiedzi na zadane pytanie.
 Obiekt po zadaniu i udzieleniu pytania wykonuje funkcje (callbacki) informujące o zadaniu pytania / udzieleniu odpowiedzi.

**Comment by maciekkwiet** [comment]
Nie rozumiem jak to ma działac xd
To ma być po prostu klasa zbierająca odpowiedzi? Zapis punktów później itp.? Dziwny ten case
