### ISSUE TITLE
Błąd z czasem i mieczem świetlnym

### ISSUE THREAD

**Issue by maciekkwiet** [KlaraGajaszek/CC2020Javascript#62]
1. Poprawić długość czasu
2. Czas powinien się zaczynać na nowo po otrzymaniu nowego pytania
3. Czas wyświetla się po zakończeniu rozgrywki
![image](https://user-images.githubusercontent.com/33134609/104756391-0bb5be80-575c-11eb-9a9a-6ad2ed7a4718.png)

**Comment by wojaneta** [comment]
@maciekkwiet o co chodzi w pkt. 2? z tego co zrozumiałam  z widoku  modala z figmy to całkowity czas całej gry to 1min i o wygranej decyduje kto w ciągu tej minuty odgadł poprawnie więcej pytań
<img width="533" alt="Screenshot 2021-01-16 at 17 04 10" src="https://user-images.githubusercontent.com/63155419/104816678-040a1e80-581d-11eb-99f0-6b34a6ec4835.png">

**Comment by maciekkwiet** [comment]
Właśnie widze, ja źle pomyślałem ale w takim razie ustawianie wyników graczy na podstawie wyniku procentowego nie ma sensu, bo załóżmy ktoś raz odpowie i bedzie to poprawna odpowiedz to nie musi dalej odpowiadać i będzie na pierwszym miejscu

**Comment by wojaneta** [comment]
to może trzeba ustalić konkretną liczbę pytań i liczyć procent poprawnych odpowiedzi do wszystkich pytań?

**Comment by maciekkwiet** [comment]
Właśie ja myślałem że to ma być stała liczba pytań :/ 
Teraz nie wiem jak to zrobić ale właśnie chciałem ustawic liczbę pytań na 20 i wtedy na każde pytanie dać np 15s
